Add Chinese documents
antfu/vue-starport pull request #33
Opened 2022-04-16 07:41 UTC by dohooo

#32

2022-04-16 07:42 UTC, dohooo commented
[Preview](https://github.com/dohooo/vue-starport)

2022-04-16 07:58 UTC, antfu requested changes

2022-04-16 07:58 UTC, antfu commented on README.md
> +  import { StarportCarrier } from "vue-starport";
Please revert the format changes

2022-04-16 10:52 UTC, antfu commented
You can use [tldraw](https://www.tldraw.com/) to open the source file https://github.com/antfu/vue-starport/blob/main/graphs/source.tldr and generate the new image.

2022-04-16 11:18 UTC, dohooo commented
> You can use [tldraw](https://www.tldraw.com/) to open the source file https://github.com/antfu/vue-starport/blob/main/graphs/source.tldr and generate the new image.

<img width="1859" alt="image" src="https://user-images.githubusercontent.com/32405058/163672949-fb65889c-a177-4c42-8411-3b4e57e9cf06.png">

There are some problems with Chinese export..

2022-04-16 11:28 UTC, dohooo commented
You can [recheck it](https://github.com/dohooo/vue-starport/blob/main/README.zh-Hans.md). I took screen short.

2022-04-17 05:03 UTC, dohooo commented
Hi @antfu , Do I need to do anything else?

2022-04-21 11:15 UTC, merged